# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pinman/Documents/pixeltrack_v0.3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pinman/Documents/pixeltrack_v0.3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pinman/Documents/pixeltrack_v0.3/CMakeFiles /home/pinman/Documents/pixeltrack_v0.3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pinman/Documents/pixeltrack_v0.3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pixeltrack

# Build rule for target.
pixeltrack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pixeltrack
.PHONY : pixeltrack

# fast build rule for target.
pixeltrack/fast:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/build
.PHONY : pixeltrack/fast

BGR2HSVdistLUT.o: BGR2HSVdistLUT.cpp.o
.PHONY : BGR2HSVdistLUT.o

# target to build an object file
BGR2HSVdistLUT.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/BGR2HSVdistLUT.cpp.o
.PHONY : BGR2HSVdistLUT.cpp.o

BGR2HSVdistLUT.i: BGR2HSVdistLUT.cpp.i
.PHONY : BGR2HSVdistLUT.i

# target to preprocess a source file
BGR2HSVdistLUT.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/BGR2HSVdistLUT.cpp.i
.PHONY : BGR2HSVdistLUT.cpp.i

BGR2HSVdistLUT.s: BGR2HSVdistLUT.cpp.s
.PHONY : BGR2HSVdistLUT.s

# target to generate assembly for a file
BGR2HSVdistLUT.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/BGR2HSVdistLUT.cpp.s
.PHONY : BGR2HSVdistLUT.cpp.s

BGR2HSVhistLUT.o: BGR2HSVhistLUT.cpp.o
.PHONY : BGR2HSVhistLUT.o

# target to build an object file
BGR2HSVhistLUT.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/BGR2HSVhistLUT.cpp.o
.PHONY : BGR2HSVhistLUT.cpp.o

BGR2HSVhistLUT.i: BGR2HSVhistLUT.cpp.i
.PHONY : BGR2HSVhistLUT.i

# target to preprocess a source file
BGR2HSVhistLUT.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/BGR2HSVhistLUT.cpp.i
.PHONY : BGR2HSVhistLUT.cpp.i

BGR2HSVhistLUT.s: BGR2HSVhistLUT.cpp.s
.PHONY : BGR2HSVhistLUT.s

# target to generate assembly for a file
BGR2HSVhistLUT.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/BGR2HSVhistLUT.cpp.s
.PHONY : BGR2HSVhistLUT.cpp.s

ColourHistLUT.o: ColourHistLUT.cpp.o
.PHONY : ColourHistLUT.o

# target to build an object file
ColourHistLUT.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/ColourHistLUT.cpp.o
.PHONY : ColourHistLUT.cpp.o

ColourHistLUT.i: ColourHistLUT.cpp.i
.PHONY : ColourHistLUT.i

# target to preprocess a source file
ColourHistLUT.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/ColourHistLUT.cpp.i
.PHONY : ColourHistLUT.cpp.i

ColourHistLUT.s: ColourHistLUT.cpp.s
.PHONY : ColourHistLUT.s

# target to generate assembly for a file
ColourHistLUT.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/ColourHistLUT.cpp.s
.PHONY : ColourHistLUT.cpp.s

Convert.o: Convert.cpp.o
.PHONY : Convert.o

# target to build an object file
Convert.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Convert.cpp.o
.PHONY : Convert.cpp.o

Convert.i: Convert.cpp.i
.PHONY : Convert.i

# target to preprocess a source file
Convert.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Convert.cpp.i
.PHONY : Convert.cpp.i

Convert.s: Convert.cpp.s
.PHONY : Convert.s

# target to generate assembly for a file
Convert.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Convert.cpp.s
.PHONY : Convert.cpp.s

Draw.o: Draw.cpp.o
.PHONY : Draw.o

# target to build an object file
Draw.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Draw.cpp.o
.PHONY : Draw.cpp.o

Draw.i: Draw.cpp.i
.PHONY : Draw.i

# target to preprocess a source file
Draw.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Draw.cpp.i
.PHONY : Draw.cpp.i

Draw.s: Draw.cpp.s
.PHONY : Draw.s

# target to generate assembly for a file
Draw.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Draw.cpp.s
.PHONY : Draw.cpp.s

Error.o: Error.cpp.o
.PHONY : Error.o

# target to build an object file
Error.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Error.cpp.o
.PHONY : Error.cpp.o

Error.i: Error.cpp.i
.PHONY : Error.i

# target to preprocess a source file
Error.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Error.cpp.i
.PHONY : Error.cpp.i

Error.s: Error.cpp.s
.PHONY : Error.s

# target to generate assembly for a file
Error.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Error.cpp.s
.PHONY : Error.cpp.s

GradDispLUT.o: GradDispLUT.cpp.o
.PHONY : GradDispLUT.o

# target to build an object file
GradDispLUT.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/GradDispLUT.cpp.o
.PHONY : GradDispLUT.cpp.o

GradDispLUT.i: GradDispLUT.cpp.i
.PHONY : GradDispLUT.i

# target to preprocess a source file
GradDispLUT.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/GradDispLUT.cpp.i
.PHONY : GradDispLUT.cpp.i

GradDispLUT.s: GradDispLUT.cpp.s
.PHONY : GradDispLUT.s

# target to generate assembly for a file
GradDispLUT.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/GradDispLUT.cpp.s
.PHONY : GradDispLUT.cpp.s

GradientModel.o: GradientModel.cpp.o
.PHONY : GradientModel.o

# target to build an object file
GradientModel.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/GradientModel.cpp.o
.PHONY : GradientModel.cpp.o

GradientModel.i: GradientModel.cpp.i
.PHONY : GradientModel.i

# target to preprocess a source file
GradientModel.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/GradientModel.cpp.i
.PHONY : GradientModel.cpp.i

GradientModel.s: GradientModel.cpp.s
.PHONY : GradientModel.s

# target to generate assembly for a file
GradientModel.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/GradientModel.cpp.s
.PHONY : GradientModel.cpp.s

HSVPixelGradientModel.o: HSVPixelGradientModel.cpp.o
.PHONY : HSVPixelGradientModel.o

# target to build an object file
HSVPixelGradientModel.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/HSVPixelGradientModel.cpp.o
.PHONY : HSVPixelGradientModel.cpp.o

HSVPixelGradientModel.i: HSVPixelGradientModel.cpp.i
.PHONY : HSVPixelGradientModel.i

# target to preprocess a source file
HSVPixelGradientModel.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/HSVPixelGradientModel.cpp.i
.PHONY : HSVPixelGradientModel.cpp.i

HSVPixelGradientModel.s: HSVPixelGradientModel.cpp.s
.PHONY : HSVPixelGradientModel.s

# target to generate assembly for a file
HSVPixelGradientModel.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/HSVPixelGradientModel.cpp.s
.PHONY : HSVPixelGradientModel.cpp.s

HSVPixelModel.o: HSVPixelModel.cpp.o
.PHONY : HSVPixelModel.o

# target to build an object file
HSVPixelModel.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/HSVPixelModel.cpp.o
.PHONY : HSVPixelModel.cpp.o

HSVPixelModel.i: HSVPixelModel.cpp.i
.PHONY : HSVPixelModel.i

# target to preprocess a source file
HSVPixelModel.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/HSVPixelModel.cpp.i
.PHONY : HSVPixelModel.cpp.i

HSVPixelModel.s: HSVPixelModel.cpp.s
.PHONY : HSVPixelModel.s

# target to generate assembly for a file
HSVPixelModel.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/HSVPixelModel.cpp.s
.PHONY : HSVPixelModel.cpp.s

Histogram.o: Histogram.cpp.o
.PHONY : Histogram.o

# target to build an object file
Histogram.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Histogram.cpp.o
.PHONY : Histogram.cpp.o

Histogram.i: Histogram.cpp.i
.PHONY : Histogram.i

# target to preprocess a source file
Histogram.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Histogram.cpp.i
.PHONY : Histogram.cpp.i

Histogram.s: Histogram.cpp.s
.PHONY : Histogram.s

# target to generate assembly for a file
Histogram.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Histogram.cpp.s
.PHONY : Histogram.cpp.s

ImageOutput.o: ImageOutput.cpp.o
.PHONY : ImageOutput.o

# target to build an object file
ImageOutput.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/ImageOutput.cpp.o
.PHONY : ImageOutput.cpp.o

ImageOutput.i: ImageOutput.cpp.i
.PHONY : ImageOutput.i

# target to preprocess a source file
ImageOutput.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/ImageOutput.cpp.i
.PHONY : ImageOutput.cpp.i

ImageOutput.s: ImageOutput.cpp.s
.PHONY : ImageOutput.s

# target to generate assembly for a file
ImageOutput.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/ImageOutput.cpp.s
.PHONY : ImageOutput.cpp.s

Output.o: Output.cpp.o
.PHONY : Output.o

# target to build an object file
Output.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Output.cpp.o
.PHONY : Output.cpp.o

Output.i: Output.cpp.i
.PHONY : Output.i

# target to preprocess a source file
Output.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Output.cpp.i
.PHONY : Output.cpp.i

Output.s: Output.cpp.s
.PHONY : Output.s

# target to generate assembly for a file
Output.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Output.cpp.s
.PHONY : Output.cpp.s

OutputTXTFile.o: OutputTXTFile.cpp.o
.PHONY : OutputTXTFile.o

# target to build an object file
OutputTXTFile.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/OutputTXTFile.cpp.o
.PHONY : OutputTXTFile.cpp.o

OutputTXTFile.i: OutputTXTFile.cpp.i
.PHONY : OutputTXTFile.i

# target to preprocess a source file
OutputTXTFile.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/OutputTXTFile.cpp.i
.PHONY : OutputTXTFile.cpp.i

OutputTXTFile.s: OutputTXTFile.cpp.s
.PHONY : OutputTXTFile.s

# target to generate assembly for a file
OutputTXTFile.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/OutputTXTFile.cpp.s
.PHONY : OutputTXTFile.cpp.s

OutputXMLFile.o: OutputXMLFile.cpp.o
.PHONY : OutputXMLFile.o

# target to build an object file
OutputXMLFile.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/OutputXMLFile.cpp.o
.PHONY : OutputXMLFile.cpp.o

OutputXMLFile.i: OutputXMLFile.cpp.i
.PHONY : OutputXMLFile.i

# target to preprocess a source file
OutputXMLFile.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/OutputXMLFile.cpp.i
.PHONY : OutputXMLFile.cpp.i

OutputXMLFile.s: OutputXMLFile.cpp.s
.PHONY : OutputXMLFile.s

# target to generate assembly for a file
OutputXMLFile.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/OutputXMLFile.cpp.s
.PHONY : OutputXMLFile.cpp.s

PixelClassColourModel.o: PixelClassColourModel.cpp.o
.PHONY : PixelClassColourModel.o

# target to build an object file
PixelClassColourModel.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/PixelClassColourModel.cpp.o
.PHONY : PixelClassColourModel.cpp.o

PixelClassColourModel.i: PixelClassColourModel.cpp.i
.PHONY : PixelClassColourModel.i

# target to preprocess a source file
PixelClassColourModel.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/PixelClassColourModel.cpp.i
.PHONY : PixelClassColourModel.cpp.i

PixelClassColourModel.s: PixelClassColourModel.cpp.s
.PHONY : PixelClassColourModel.s

# target to generate assembly for a file
PixelClassColourModel.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/PixelClassColourModel.cpp.s
.PHONY : PixelClassColourModel.cpp.s

RandomGenerator.o: RandomGenerator.cpp.o
.PHONY : RandomGenerator.o

# target to build an object file
RandomGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/RandomGenerator.cpp.o
.PHONY : RandomGenerator.cpp.o

RandomGenerator.i: RandomGenerator.cpp.i
.PHONY : RandomGenerator.i

# target to preprocess a source file
RandomGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/RandomGenerator.cpp.i
.PHONY : RandomGenerator.cpp.i

RandomGenerator.s: RandomGenerator.cpp.s
.PHONY : RandomGenerator.s

# target to generate assembly for a file
RandomGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/RandomGenerator.cpp.s
.PHONY : RandomGenerator.cpp.s

Rectangle.o: Rectangle.cpp.o
.PHONY : Rectangle.o

# target to build an object file
Rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Rectangle.cpp.o
.PHONY : Rectangle.cpp.o

Rectangle.i: Rectangle.cpp.i
.PHONY : Rectangle.i

# target to preprocess a source file
Rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Rectangle.cpp.i
.PHONY : Rectangle.cpp.i

Rectangle.s: Rectangle.cpp.s
.PHONY : Rectangle.s

# target to generate assembly for a file
Rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Rectangle.cpp.s
.PHONY : Rectangle.cpp.s

Timer.o: Timer.cpp.o
.PHONY : Timer.o

# target to build an object file
Timer.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Timer.cpp.o
.PHONY : Timer.cpp.o

Timer.i: Timer.cpp.i
.PHONY : Timer.i

# target to preprocess a source file
Timer.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Timer.cpp.i
.PHONY : Timer.cpp.i

Timer.s: Timer.cpp.s
.PHONY : Timer.s

# target to generate assembly for a file
Timer.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/Timer.cpp.s
.PHONY : Timer.cpp.s

VideoInput.o: VideoInput.cpp.o
.PHONY : VideoInput.o

# target to build an object file
VideoInput.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoInput.cpp.o
.PHONY : VideoInput.cpp.o

VideoInput.i: VideoInput.cpp.i
.PHONY : VideoInput.i

# target to preprocess a source file
VideoInput.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoInput.cpp.i
.PHONY : VideoInput.cpp.i

VideoInput.s: VideoInput.cpp.s
.PHONY : VideoInput.s

# target to generate assembly for a file
VideoInput.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoInput.cpp.s
.PHONY : VideoInput.cpp.s

VideoInputFile.o: VideoInputFile.cpp.o
.PHONY : VideoInputFile.o

# target to build an object file
VideoInputFile.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoInputFile.cpp.o
.PHONY : VideoInputFile.cpp.o

VideoInputFile.i: VideoInputFile.cpp.i
.PHONY : VideoInputFile.i

# target to preprocess a source file
VideoInputFile.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoInputFile.cpp.i
.PHONY : VideoInputFile.cpp.i

VideoInputFile.s: VideoInputFile.cpp.s
.PHONY : VideoInputFile.s

# target to generate assembly for a file
VideoInputFile.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoInputFile.cpp.s
.PHONY : VideoInputFile.cpp.s

VideoInputVOT.o: VideoInputVOT.cpp.o
.PHONY : VideoInputVOT.o

# target to build an object file
VideoInputVOT.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoInputVOT.cpp.o
.PHONY : VideoInputVOT.cpp.o

VideoInputVOT.i: VideoInputVOT.cpp.i
.PHONY : VideoInputVOT.i

# target to preprocess a source file
VideoInputVOT.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoInputVOT.cpp.i
.PHONY : VideoInputVOT.cpp.i

VideoInputVOT.s: VideoInputVOT.cpp.s
.PHONY : VideoInputVOT.s

# target to generate assembly for a file
VideoInputVOT.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoInputVOT.cpp.s
.PHONY : VideoInputVOT.cpp.s

VideoOutput.o: VideoOutput.cpp.o
.PHONY : VideoOutput.o

# target to build an object file
VideoOutput.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoOutput.cpp.o
.PHONY : VideoOutput.cpp.o

VideoOutput.i: VideoOutput.cpp.i
.PHONY : VideoOutput.i

# target to preprocess a source file
VideoOutput.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoOutput.cpp.i
.PHONY : VideoOutput.cpp.i

VideoOutput.s: VideoOutput.cpp.s
.PHONY : VideoOutput.s

# target to generate assembly for a file
VideoOutput.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/VideoOutput.cpp.s
.PHONY : VideoOutput.cpp.s

pixeltrack.o: pixeltrack.cpp.o
.PHONY : pixeltrack.o

# target to build an object file
pixeltrack.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/pixeltrack.cpp.o
.PHONY : pixeltrack.cpp.o

pixeltrack.i: pixeltrack.cpp.i
.PHONY : pixeltrack.i

# target to preprocess a source file
pixeltrack.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/pixeltrack.cpp.i
.PHONY : pixeltrack.cpp.i

pixeltrack.s: pixeltrack.cpp.s
.PHONY : pixeltrack.s

# target to generate assembly for a file
pixeltrack.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/pixeltrack.cpp.s
.PHONY : pixeltrack.cpp.s

util.o: util.cpp.o
.PHONY : util.o

# target to build an object file
util.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/util.cpp.o
.PHONY : util.cpp.o

util.i: util.cpp.i
.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s
.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/util.cpp.s
.PHONY : util.cpp.s

utils_cv.o: utils_cv.cpp.o
.PHONY : utils_cv.o

# target to build an object file
utils_cv.cpp.o:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/utils_cv.cpp.o
.PHONY : utils_cv.cpp.o

utils_cv.i: utils_cv.cpp.i
.PHONY : utils_cv.i

# target to preprocess a source file
utils_cv.cpp.i:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/utils_cv.cpp.i
.PHONY : utils_cv.cpp.i

utils_cv.s: utils_cv.cpp.s
.PHONY : utils_cv.s

# target to generate assembly for a file
utils_cv.cpp.s:
	$(MAKE) -f CMakeFiles/pixeltrack.dir/build.make CMakeFiles/pixeltrack.dir/utils_cv.cpp.s
.PHONY : utils_cv.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pixeltrack"
	@echo "... rebuild_cache"
	@echo "... BGR2HSVdistLUT.o"
	@echo "... BGR2HSVdistLUT.i"
	@echo "... BGR2HSVdistLUT.s"
	@echo "... BGR2HSVhistLUT.o"
	@echo "... BGR2HSVhistLUT.i"
	@echo "... BGR2HSVhistLUT.s"
	@echo "... ColourHistLUT.o"
	@echo "... ColourHistLUT.i"
	@echo "... ColourHistLUT.s"
	@echo "... Convert.o"
	@echo "... Convert.i"
	@echo "... Convert.s"
	@echo "... Draw.o"
	@echo "... Draw.i"
	@echo "... Draw.s"
	@echo "... Error.o"
	@echo "... Error.i"
	@echo "... Error.s"
	@echo "... GradDispLUT.o"
	@echo "... GradDispLUT.i"
	@echo "... GradDispLUT.s"
	@echo "... GradientModel.o"
	@echo "... GradientModel.i"
	@echo "... GradientModel.s"
	@echo "... HSVPixelGradientModel.o"
	@echo "... HSVPixelGradientModel.i"
	@echo "... HSVPixelGradientModel.s"
	@echo "... HSVPixelModel.o"
	@echo "... HSVPixelModel.i"
	@echo "... HSVPixelModel.s"
	@echo "... Histogram.o"
	@echo "... Histogram.i"
	@echo "... Histogram.s"
	@echo "... ImageOutput.o"
	@echo "... ImageOutput.i"
	@echo "... ImageOutput.s"
	@echo "... Output.o"
	@echo "... Output.i"
	@echo "... Output.s"
	@echo "... OutputTXTFile.o"
	@echo "... OutputTXTFile.i"
	@echo "... OutputTXTFile.s"
	@echo "... OutputXMLFile.o"
	@echo "... OutputXMLFile.i"
	@echo "... OutputXMLFile.s"
	@echo "... PixelClassColourModel.o"
	@echo "... PixelClassColourModel.i"
	@echo "... PixelClassColourModel.s"
	@echo "... RandomGenerator.o"
	@echo "... RandomGenerator.i"
	@echo "... RandomGenerator.s"
	@echo "... Rectangle.o"
	@echo "... Rectangle.i"
	@echo "... Rectangle.s"
	@echo "... Timer.o"
	@echo "... Timer.i"
	@echo "... Timer.s"
	@echo "... VideoInput.o"
	@echo "... VideoInput.i"
	@echo "... VideoInput.s"
	@echo "... VideoInputFile.o"
	@echo "... VideoInputFile.i"
	@echo "... VideoInputFile.s"
	@echo "... VideoInputVOT.o"
	@echo "... VideoInputVOT.i"
	@echo "... VideoInputVOT.s"
	@echo "... VideoOutput.o"
	@echo "... VideoOutput.i"
	@echo "... VideoOutput.s"
	@echo "... pixeltrack.o"
	@echo "... pixeltrack.i"
	@echo "... pixeltrack.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
	@echo "... utils_cv.o"
	@echo "... utils_cv.i"
	@echo "... utils_cv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

